global:
  storageClass: "remote-disk"

auth:
  enabled: true

master:
  count: 1
  persistence:
    enabled: true
    size: 2Gi

replica:
  replicaCount: 1
  persistence:
    enabled: true
    size: 2Gi

sentinel:
  enabled: false
